### ISSUE TITLE
Failed to subscribe

### ISSUE THREAD

**Issue by lonormaly** [pushy-me/pushy-sdk-web#1]
Just recently the service stopped working:

Error: Failed to subscribe the device: Registration failed - push service error
    at Object.<anonymous> (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:1:2020)
    at r (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:29270)
    at Generator._invoke (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:30390)
    at Generator.t.<computed> [as throw] (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:29449)
    at r (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:29270)
    at e (https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:29505)
    at https://sdk.pushy.me/web/1.0.5/pushy-sdk.js:3:29683

our code didn't change...

Any idea what happened?

**Comment by lonormaly** [comment]
Note: seems to work in Chrome. I'm using Brave

**Comment by pushy-me** [comment]
Hi @lonormaly,
Thanks so much for reporting this issue.

The [Brave browser](https://brave.com/), out of the box, [does not support Web Push notifications](https://github.com/brave/brave-browser/issues/2301) when it is first installed. We understand this is extremely frustrating. The user must enable a setting called `"Use Google Services for Push Messaging"` in the Browser Settings for Web Push to be supported:
```
brave://settings/?search=push+messaging
```

Once enabled, and the browser is restarted, you can use the Pushy Demo page to test Web Push notifications to Brave: 
https://pushy.me/docs/resources/demo

More information about this issue and the required workaround is available in Brave's GitHub repository: 
https://github.com/brave/brave-browser/issues/2301#issuecomment-568440814

Please let us know if you have any further questions.

**Comment by pushy-me** [comment]
Hi @lonormaly,
We've added an instruction for Brave users to enable the relevant setting in https://github.com/pushy-me/pushy-sdk-web/commit/bb2e50867ca215807bca95f667f9ed6aefe260cc and published to `npm` in `1.0.6`.

**Comment by mayeaux** [comment]
That's interesting. I enabled that, but it's still not working, but at least I don't get that error anymore.

**Comment by pushy-me** [comment]
Hi @mayeaux,
1) Did you restart the browser afterwards as instructed?
2) Are you located in China? Google's servers are blocked there.
3) Are you using the Pushy Demo page to test?
https://pushy.me/docs/resources/demo
4) Does it say "notification sent" but nothing is received?
